[2025-04-17T13:17:10.269+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T13:17:10.325+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline.extract_yellow manual__2025-04-17T13:15:19.803844+00:00 [queued]>
[2025-04-17T13:17:10.340+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline.extract_yellow manual__2025-04-17T13:15:19.803844+00:00 [queued]>
[2025-04-17T13:17:10.341+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-04-17T13:17:10.358+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): extract_yellow> on 2025-04-17 13:15:19.803844+00:00
[2025-04-17T13:17:10.365+0000] {standard_task_runner.py:72} INFO - Started process 2586 to run task
[2025-04-17T13:17:10.367+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline', 'extract_yellow', 'manual__2025-04-17T13:15:19.803844+00:00', '--job-id', '863', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmpd7ecbf9e']
[2025-04-17T13:17:10.369+0000] {standard_task_runner.py:105} INFO - Job 863: Subtask extract_yellow
[2025-04-17T13:17:10.626+0000] {task_command.py:467} INFO - Running <TaskInstance: full_pipeline.extract_yellow manual__2025-04-17T13:15:19.803844+00:00 [running]> on host 772d115850d3
[2025-04-17T13:17:10.831+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='full_pipeline' AIRFLOW_CTX_TASK_ID='extract_yellow' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T13:15:19.803844+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T13:15:19.803844+00:00'
[2025-04-17T13:17:10.832+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T13:17:10.844+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-17T13:17:10.845+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/pipeline/extract/fetch_yellow_trip.py']
[2025-04-17T13:17:10.854+0000] {subprocess.py:99} INFO - Output:
[2025-04-17T13:17:11.979+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-17T13:17:11.979+0000] {subprocess.py:106} INFO -   File "/opt/airflow/pipeline/extract/fetch_yellow_trip.py", line 26, in <module>
[2025-04-17T13:17:11.987+0000] {subprocess.py:106} INFO -     upload_to_minio(
[2025-04-17T13:17:11.988+0000] {subprocess.py:106} INFO -   File "/opt/airflow/pipeline/extract/fetch_yellow_trip.py", line 22, in upload_to_minio
[2025-04-17T13:17:11.993+0000] {subprocess.py:106} INFO -     s3.upload_file(file_path, bucket_name, object_name)
[2025-04-17T13:17:11.994+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/inject.py", line 145, in upload_file
[2025-04-17T13:17:11.994+0000] {subprocess.py:106} INFO -     return transfer.upload_file(
[2025-04-17T13:17:11.995+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T13:17:11.996+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/transfer.py", line 372, in upload_file
[2025-04-17T13:17:11.996+0000] {subprocess.py:106} INFO -     future.result()
[2025-04-17T13:17:11.997+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 103, in result
[2025-04-17T13:17:11.997+0000] {subprocess.py:106} INFO -     return self._coordinator.result()
[2025-04-17T13:17:11.998+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T13:17:11.999+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 264, in result
[2025-04-17T13:17:12.000+0000] {subprocess.py:106} INFO -     raise self._exception
[2025-04-17T13:17:12.000+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/tasks.py", line 265, in _main
[2025-04-17T13:17:12.001+0000] {subprocess.py:106} INFO -     self._submit(transfer_future=transfer_future, **kwargs)
[2025-04-17T13:17:12.001+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/upload.py", line 589, in _submit
[2025-04-17T13:17:12.002+0000] {subprocess.py:106} INFO -     upload_input_manager.provide_transfer_size(transfer_future)
[2025-04-17T13:17:12.003+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/upload.py", line 244, in provide_transfer_size
[2025-04-17T13:17:12.004+0000] {subprocess.py:106} INFO -     self._osutil.get_file_size(transfer_future.meta.call_args.fileobj)
[2025-04-17T13:17:12.004+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/utils.py", line 254, in get_file_size
[2025-04-17T13:17:12.005+0000] {subprocess.py:106} INFO -     return os.path.getsize(filename)
[2025-04-17T13:17:12.006+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T13:17:12.007+0000] {subprocess.py:106} INFO -   File "<frozen genericpath>", line 62, in getsize
[2025-04-17T13:17:12.009+0000] {subprocess.py:106} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'yellow_tripdata_2023-01.parquet'
[2025-04-17T13:17:12.110+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-17T13:17:12.162+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-17T13:17:12.173+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=full_pipeline, task_id=extract_yellow, run_id=manual__2025-04-17T13:15:19.803844+00:00, execution_date=20250417T131519, start_date=20250417T131710, end_date=20250417T131712
[2025-04-17T13:17:12.199+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-17T13:17:12.200+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 863 for task extract_yellow (Bash command failed. The command returned a non-zero exit code 1.; 2586)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-17T13:17:12.230+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-17T13:17:12.295+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T13:17:12.298+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
