[2025-04-17T12:23:03.908+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T12:23:03.963+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline.extract_yellow manual__2025-04-17T12:22:57.297448+00:00 [queued]>
[2025-04-17T12:23:03.978+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline.extract_yellow manual__2025-04-17T12:22:57.297448+00:00 [queued]>
[2025-04-17T12:23:03.979+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-04-17T12:23:03.997+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): extract_yellow> on 2025-04-17 12:22:57.297448+00:00
[2025-04-17T12:23:04.005+0000] {standard_task_runner.py:72} INFO - Started process 203 to run task
[2025-04-17T12:23:04.007+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline', 'extract_yellow', 'manual__2025-04-17T12:22:57.297448+00:00', '--job-id', '854', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmpl5f7t7sn']
[2025-04-17T12:23:04.010+0000] {standard_task_runner.py:105} INFO - Job 854: Subtask extract_yellow
[2025-04-17T12:23:04.175+0000] {task_command.py:467} INFO - Running <TaskInstance: full_pipeline.extract_yellow manual__2025-04-17T12:22:57.297448+00:00 [running]> on host d139622d7ee8
[2025-04-17T12:23:04.392+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='full_pipeline' AIRFLOW_CTX_TASK_ID='extract_yellow' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T12:22:57.297448+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T12:22:57.297448+00:00'
[2025-04-17T12:23:04.393+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T12:23:04.410+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-17T12:23:04.412+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/pipeline/extract/fetch_yellow_trip.py']
[2025-04-17T12:23:04.422+0000] {subprocess.py:99} INFO - Output:
[2025-04-17T12:28:11.658+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-17T12:28:11.664+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
[2025-04-17T12:28:11.665+0000] {subprocess.py:106} INFO -     sock = connection.create_connection(
[2025-04-17T12:28:11.666+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.666+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
[2025-04-17T12:28:11.667+0000] {subprocess.py:106} INFO -     raise err
[2025-04-17T12:28:11.668+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
[2025-04-17T12:28:11.668+0000] {subprocess.py:106} INFO -     sock.connect(sa)
[2025-04-17T12:28:11.669+0000] {subprocess.py:106} INFO - TimeoutError: timed out
[2025-04-17T12:28:11.671+0000] {subprocess.py:106} INFO - 
[2025-04-17T12:28:11.671+0000] {subprocess.py:106} INFO - The above exception was the direct cause of the following exception:
[2025-04-17T12:28:11.672+0000] {subprocess.py:106} INFO - 
[2025-04-17T12:28:11.673+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-17T12:28:11.673+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/httpsession.py", line 464, in send
[2025-04-17T12:28:11.674+0000] {subprocess.py:106} INFO -     urllib_response = conn.urlopen(
[2025-04-17T12:28:11.675+0000] {subprocess.py:106} INFO -                       ^^^^^^^^^^^^^
[2025-04-17T12:28:11.675+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
[2025-04-17T12:28:11.676+0000] {subprocess.py:106} INFO -     retries = retries.increment(
[2025-04-17T12:28:11.677+0000] {subprocess.py:106} INFO -               ^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.678+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 449, in increment
[2025-04-17T12:28:11.679+0000] {subprocess.py:106} INFO -     raise reraise(type(error), error, _stacktrace)
[2025-04-17T12:28:11.679+0000] {subprocess.py:106} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.680+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 39, in reraise
[2025-04-17T12:28:11.681+0000] {subprocess.py:106} INFO -     raise value
[2025-04-17T12:28:11.681+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
[2025-04-17T12:28:11.681+0000] {subprocess.py:106} INFO -     response = self._make_request(
[2025-04-17T12:28:11.682+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.683+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
[2025-04-17T12:28:11.683+0000] {subprocess.py:106} INFO -     conn.request(
[2025-04-17T12:28:11.683+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/awsrequest.py", line 96, in request
[2025-04-17T12:28:11.684+0000] {subprocess.py:106} INFO -     rval = super().request(method, url, body, headers, *args, **kwargs)
[2025-04-17T12:28:11.685+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.685+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
[2025-04-17T12:28:11.685+0000] {subprocess.py:106} INFO -     self.endheaders()
[2025-04-17T12:28:11.686+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
[2025-04-17T12:28:11.686+0000] {subprocess.py:106} INFO -     self._send_output(message_body, encode_chunked=encode_chunked)
[2025-04-17T12:28:11.686+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/awsrequest.py", line 123, in _send_output
[2025-04-17T12:28:11.686+0000] {subprocess.py:106} INFO -     self.send(msg)
[2025-04-17T12:28:11.687+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/awsrequest.py", line 223, in send
[2025-04-17T12:28:11.687+0000] {subprocess.py:106} INFO -     return super().send(str)
[2025-04-17T12:28:11.687+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.687+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
[2025-04-17T12:28:11.688+0000] {subprocess.py:106} INFO -     self.connect()
[2025-04-17T12:28:11.688+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
[2025-04-17T12:28:11.688+0000] {subprocess.py:106} INFO -     self.sock = self._new_conn()
[2025-04-17T12:28:11.689+0000] {subprocess.py:106} INFO -                 ^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.689+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 208, in _new_conn
[2025-04-17T12:28:11.690+0000] {subprocess.py:106} INFO -     raise ConnectTimeoutError(
[2025-04-17T12:28:11.690+0000] {subprocess.py:106} INFO - urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7f53eb124260>, 'Connection to 172.17.16.1 timed out. (connect timeout=60)')
[2025-04-17T12:28:11.691+0000] {subprocess.py:106} INFO - 
[2025-04-17T12:28:11.692+0000] {subprocess.py:106} INFO - During handling of the above exception, another exception occurred:
[2025-04-17T12:28:11.692+0000] {subprocess.py:106} INFO - 
[2025-04-17T12:28:11.693+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-17T12:28:11.694+0000] {subprocess.py:106} INFO -   File "/opt/airflow/pipeline/extract/fetch_yellow_trip.py", line 26, in <module>
[2025-04-17T12:28:11.694+0000] {subprocess.py:106} INFO -     upload_to_minio(
[2025-04-17T12:28:11.695+0000] {subprocess.py:106} INFO -   File "/opt/airflow/pipeline/extract/fetch_yellow_trip.py", line 17, in upload_to_minio
[2025-04-17T12:28:11.695+0000] {subprocess.py:106} INFO -     buckets = [bucket['Name'] for bucket in s3.list_buckets()['Buckets']]
[2025-04-17T12:28:11.696+0000] {subprocess.py:106} INFO -                                             ^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.696+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
[2025-04-17T12:28:11.697+0000] {subprocess.py:106} INFO -     return self._make_api_call(operation_name, kwargs)
[2025-04-17T12:28:11.697+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.698+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1005, in _make_api_call
[2025-04-17T12:28:11.698+0000] {subprocess.py:106} INFO -     http, parsed_response = self._make_request(
[2025-04-17T12:28:11.698+0000] {subprocess.py:106} INFO -                             ^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.699+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1029, in _make_request
[2025-04-17T12:28:11.699+0000] {subprocess.py:106} INFO -     return self._endpoint.make_request(operation_model, request_dict)
[2025-04-17T12:28:11.700+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.700+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 119, in make_request
[2025-04-17T12:28:11.700+0000] {subprocess.py:106} INFO -     return self._send_request(request_dict, operation_model)
[2025-04-17T12:28:11.701+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.701+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 200, in _send_request
[2025-04-17T12:28:11.702+0000] {subprocess.py:106} INFO -     while self._needs_retry(
[2025-04-17T12:28:11.702+0000] {subprocess.py:106} INFO -           ^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.703+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 360, in _needs_retry
[2025-04-17T12:28:11.703+0000] {subprocess.py:106} INFO -     responses = self._event_emitter.emit(
[2025-04-17T12:28:11.703+0000] {subprocess.py:106} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.704+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
[2025-04-17T12:28:11.705+0000] {subprocess.py:106} INFO -     return self._emitter.emit(aliased_event_name, **kwargs)
[2025-04-17T12:28:11.705+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.706+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
[2025-04-17T12:28:11.706+0000] {subprocess.py:106} INFO -     return self._emit(event_name, kwargs)
[2025-04-17T12:28:11.707+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.707+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
[2025-04-17T12:28:11.708+0000] {subprocess.py:106} INFO -     response = handler(**kwargs)
[2025-04-17T12:28:11.708+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.709+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py", line 207, in __call__
[2025-04-17T12:28:11.709+0000] {subprocess.py:106} INFO -     if self._checker(**checker_kwargs):
[2025-04-17T12:28:11.710+0000] {subprocess.py:106} INFO -        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.710+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py", line 284, in __call__
[2025-04-17T12:28:11.711+0000] {subprocess.py:106} INFO -     should_retry = self._should_retry(
[2025-04-17T12:28:11.712+0000] {subprocess.py:106} INFO -                    ^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.712+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py", line 320, in _should_retry
[2025-04-17T12:28:11.712+0000] {subprocess.py:106} INFO -     return self._checker(attempt_number, response, caught_exception)
[2025-04-17T12:28:11.713+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.713+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py", line 363, in __call__
[2025-04-17T12:28:11.714+0000] {subprocess.py:106} INFO -     checker_response = checker(
[2025-04-17T12:28:11.714+0000] {subprocess.py:106} INFO -                        ^^^^^^^^
[2025-04-17T12:28:11.715+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py", line 247, in __call__
[2025-04-17T12:28:11.715+0000] {subprocess.py:106} INFO -     return self._check_caught_exception(
[2025-04-17T12:28:11.716+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.716+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
[2025-04-17T12:28:11.716+0000] {subprocess.py:106} INFO -     raise caught_exception
[2025-04-17T12:28:11.717+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 279, in _do_get_response
[2025-04-17T12:28:11.717+0000] {subprocess.py:106} INFO -     http_response = self._send(request)
[2025-04-17T12:28:11.718+0000] {subprocess.py:106} INFO -                     ^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.719+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 383, in _send
[2025-04-17T12:28:11.720+0000] {subprocess.py:106} INFO -     return self.http_session.send(request)
[2025-04-17T12:28:11.720+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T12:28:11.721+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/botocore/httpsession.py", line 499, in send
[2025-04-17T12:28:11.721+0000] {subprocess.py:106} INFO -     raise ConnectTimeoutError(endpoint_url=request.url, error=e)
[2025-04-17T12:28:11.722+0000] {subprocess.py:106} INFO - botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://172.17.16.1:9002/"
[2025-04-17T12:28:11.840+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-17T12:28:11.905+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-17T12:28:11.923+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=full_pipeline, task_id=extract_yellow, run_id=manual__2025-04-17T12:22:57.297448+00:00, execution_date=20250417T122257, start_date=20250417T122303, end_date=20250417T122811
[2025-04-17T12:28:11.968+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-17T12:28:11.969+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 854 for task extract_yellow (Bash command failed. The command returned a non-zero exit code 1.; 203)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-17T12:28:12.003+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-17T12:28:12.077+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T12:28:12.080+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-17T12:34:45.535+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T12:34:45.605+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline.extract_yellow manual__2025-04-17T12:22:57.297448+00:00 [up_for_retry]>
[2025-04-17T12:34:45.622+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline.extract_yellow manual__2025-04-17T12:22:57.297448+00:00 [up_for_retry]>
[2025-04-17T12:34:45.623+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-04-17T12:34:45.647+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): extract_yellow> on 2025-04-17 12:22:57.297448+00:00
[2025-04-17T12:34:45.655+0000] {standard_task_runner.py:72} INFO - Started process 350 to run task
[2025-04-17T12:34:45.671+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline', 'extract_yellow', 'manual__2025-04-17T12:22:57.297448+00:00', '--job-id', '856', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmp2mfpwxcl']
[2025-04-17T12:34:45.678+0000] {standard_task_runner.py:105} INFO - Job 856: Subtask extract_yellow
[2025-04-17T12:34:45.909+0000] {task_command.py:467} INFO - Running <TaskInstance: full_pipeline.extract_yellow manual__2025-04-17T12:22:57.297448+00:00 [running]> on host d139622d7ee8
[2025-04-17T12:34:46.268+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='full_pipeline' AIRFLOW_CTX_TASK_ID='extract_yellow' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T12:22:57.297448+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T12:22:57.297448+00:00'
[2025-04-17T12:34:46.272+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T12:34:46.317+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-17T12:34:46.321+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/pipeline/extract/fetch_yellow_trip.py']
[2025-04-17T12:34:46.335+0000] {subprocess.py:99} INFO - Output:
