[2025-03-30T22:12:25.281+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T22:12:25.449+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [queued]>
[2025-03-30T22:12:25.463+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [queued]>
[2025-03-30T22:12:25.463+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-03-30T22:12:25.482+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): daily_forecast> on 2025-03-29 04:00:00+00:00
[2025-03-30T22:12:25.494+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'paris_air_quality_prod', 'daily_forecast', 'scheduled__2025-03-29T04:00:00+00:00', '--job-id', '642', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmpggoyz205']
[2025-03-30T22:12:25.497+0000] {standard_task_runner.py:105} INFO - Job 642: Subtask daily_forecast
[2025-03-30T22:12:25.499+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1483) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T22:12:25.500+0000] {standard_task_runner.py:72} INFO - Started process 1508 to run task
[2025-03-30T22:12:25.676+0000] {task_command.py:467} INFO - Running <TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [running]> on host 04906466de51
[2025-03-30T22:12:25.862+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='paris_air_quality_prod' AIRFLOW_CTX_TASK_ID='daily_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T04:00:00+00:00'
[2025-03-30T22:12:25.863+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-30T22:12:25.876+0000] {data_enriched_predict.py:197} INFO - Initialisation du workflow de prévision
[2025-03-30T22:12:25.923+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-30T22:12:27.157+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/data_enriched_predict.py:209 FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
[2025-03-30T22:12:27.160+0000] {data_enriched_predict.py:273} ERROR - Échec du workflow: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True, at position 160
Traceback (most recent call last):
  File "/opt/airflow/dags/data_enriched_predict.py", line 212, in train_and_forecast
    training_data = prepare_training_data(historical)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 149, in prepare_training_data
    historical['timestamp'] = pd.to_datetime(historical['timestamp']).dt.tz_convert(CITY_CONFIG['timezone'])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 1112, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 490, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/datetimes.py", line 2346, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "tslib.pyx", line 403, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 552, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 480, in pandas._libs.tslib.array_to_datetime
  File "conversion.pyx", line 712, in pandas._libs.tslibs.conversion.convert_timezone
ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True, at position 160
[2025-03-30T22:12:27.172+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 212, in train_and_forecast
    training_data = prepare_training_data(historical)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 149, in prepare_training_data
    historical['timestamp'] = pd.to_datetime(historical['timestamp']).dt.tz_convert(CITY_CONFIG['timezone'])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 1112, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 490, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/datetimes.py", line 2346, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "tslib.pyx", line 403, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 552, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 480, in pandas._libs.tslib.array_to_datetime
  File "conversion.pyx", line 712, in pandas._libs.tslibs.conversion.convert_timezone
ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True, at position 160
[2025-03-30T22:12:27.223+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=paris_air_quality_prod, task_id=daily_forecast, run_id=scheduled__2025-03-29T04:00:00+00:00, execution_date=20250329T040000, start_date=20250330T221225, end_date=20250330T221227
[2025-03-30T22:12:27.248+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-30T22:12:27.249+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 642 for task daily_forecast (Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True, at position 160; 1508)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 212, in train_and_forecast
    training_data = prepare_training_data(historical)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 149, in prepare_training_data
    historical['timestamp'] = pd.to_datetime(historical['timestamp']).dt.tz_convert(CITY_CONFIG['timezone'])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 1112, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 490, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/datetimes.py", line 2346, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "tslib.pyx", line 403, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 552, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 480, in pandas._libs.tslib.array_to_datetime
  File "conversion.pyx", line 712, in pandas._libs.tslibs.conversion.convert_timezone
ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True, at position 160
[2025-03-30T22:12:27.285+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T22:12:27.342+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T22:12:27.344+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-30T22:19:02.026+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T22:19:02.086+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [queued]>
[2025-03-30T22:19:02.101+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [queued]>
[2025-03-30T22:19:02.102+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-03-30T22:19:02.119+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): daily_forecast> on 2025-03-29 04:00:00+00:00
[2025-03-30T22:19:02.129+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'paris_air_quality_prod', 'daily_forecast', 'scheduled__2025-03-29T04:00:00+00:00', '--job-id', '644', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmpacvqh0n9']
[2025-03-30T22:19:02.132+0000] {standard_task_runner.py:105} INFO - Job 644: Subtask daily_forecast
[2025-03-30T22:19:02.132+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1749) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T22:19:02.133+0000] {standard_task_runner.py:72} INFO - Started process 1776 to run task
[2025-03-30T22:19:02.294+0000] {task_command.py:467} INFO - Running <TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [running]> on host 04906466de51
[2025-03-30T22:19:02.594+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='paris_air_quality_prod' AIRFLOW_CTX_TASK_ID='daily_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T04:00:00+00:00'
[2025-03-30T22:19:02.595+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-30T22:19:02.608+0000] {data_enriched_predict.py:154} INFO - Début du workflow de prévision
[2025-03-30T22:19:02.657+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-30T22:19:03.844+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/data_enriched_predict.py:173 FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
[2025-03-30T22:19:03.866+0000] {data_enriched_predict.py:248} ERROR - Échec du workflow: Données insuffisantes: 0 enregistrements
Traceback (most recent call last):
  File "/opt/airflow/dags/data_enriched_predict.py", line 178, in train_and_forecast
    raise ValueError(f"Données insuffisantes: {len(training_data)} enregistrements")
ValueError: Données insuffisantes: 0 enregistrements
[2025-03-30T22:19:03.875+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 178, in train_and_forecast
    raise ValueError(f"Données insuffisantes: {len(training_data)} enregistrements")
ValueError: Données insuffisantes: 0 enregistrements
[2025-03-30T22:19:03.926+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=paris_air_quality_prod, task_id=daily_forecast, run_id=scheduled__2025-03-29T04:00:00+00:00, execution_date=20250329T040000, start_date=20250330T221902, end_date=20250330T221903
[2025-03-30T22:19:03.950+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-30T22:19:03.951+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 644 for task daily_forecast (Données insuffisantes: 0 enregistrements; 1776)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 178, in train_and_forecast
    raise ValueError(f"Données insuffisantes: {len(training_data)} enregistrements")
ValueError: Données insuffisantes: 0 enregistrements
[2025-03-30T22:19:03.997+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T22:19:04.053+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T22:19:04.055+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-30T22:20:06.407+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T22:20:06.454+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [queued]>
[2025-03-30T22:20:06.466+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [queued]>
[2025-03-30T22:20:06.466+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-03-30T22:20:06.482+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): daily_forecast> on 2025-03-29 04:00:00+00:00
[2025-03-30T22:20:06.491+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'paris_air_quality_prod', 'daily_forecast', 'scheduled__2025-03-29T04:00:00+00:00', '--job-id', '646', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmpmfgo_dcc']
[2025-03-30T22:20:06.494+0000] {standard_task_runner.py:105} INFO - Job 646: Subtask daily_forecast
[2025-03-30T22:20:06.494+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1835) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T22:20:06.495+0000] {standard_task_runner.py:72} INFO - Started process 1860 to run task
[2025-03-30T22:20:06.643+0000] {task_command.py:467} INFO - Running <TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [running]> on host 04906466de51
[2025-03-30T22:20:06.931+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='paris_air_quality_prod' AIRFLOW_CTX_TASK_ID='daily_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T04:00:00+00:00'
[2025-03-30T22:20:06.933+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-30T22:20:06.959+0000] {data_enriched_predict.py:154} INFO - Début du workflow de prévision
[2025-03-30T22:20:07.113+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-30T22:20:08.266+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/data_enriched_predict.py:173 FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
[2025-03-30T22:20:08.275+0000] {data_enriched_predict.py:248} ERROR - Échec du workflow: Données insuffisantes: 0 enregistrements
Traceback (most recent call last):
  File "/opt/airflow/dags/data_enriched_predict.py", line 178, in train_and_forecast
    raise ValueError(f"Données insuffisantes: {len(training_data)} enregistrements")
ValueError: Données insuffisantes: 0 enregistrements
[2025-03-30T22:20:08.283+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 178, in train_and_forecast
    raise ValueError(f"Données insuffisantes: {len(training_data)} enregistrements")
ValueError: Données insuffisantes: 0 enregistrements
[2025-03-30T22:20:08.331+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=paris_air_quality_prod, task_id=daily_forecast, run_id=scheduled__2025-03-29T04:00:00+00:00, execution_date=20250329T040000, start_date=20250330T222006, end_date=20250330T222008
[2025-03-30T22:20:08.355+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-30T22:20:08.356+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 646 for task daily_forecast (Données insuffisantes: 0 enregistrements; 1860)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 178, in train_and_forecast
    raise ValueError(f"Données insuffisantes: {len(training_data)} enregistrements")
ValueError: Données insuffisantes: 0 enregistrements
[2025-03-30T22:20:08.403+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T22:20:08.459+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T22:20:08.461+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-30T22:51:31.738+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T22:51:31.782+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [queued]>
[2025-03-30T22:51:31.793+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [queued]>
[2025-03-30T22:51:31.794+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-03-30T22:51:31.808+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): daily_forecast> on 2025-03-29 04:00:00+00:00
[2025-03-30T22:51:31.816+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'paris_air_quality_prod', 'daily_forecast', 'scheduled__2025-03-29T04:00:00+00:00', '--job-id', '661', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmpdn5q5bwc']
[2025-03-30T22:51:31.819+0000] {standard_task_runner.py:105} INFO - Job 661: Subtask daily_forecast
[2025-03-30T22:51:31.820+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3504) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T22:51:31.820+0000] {standard_task_runner.py:72} INFO - Started process 3529 to run task
[2025-03-30T22:51:31.959+0000] {task_command.py:467} INFO - Running <TaskInstance: paris_air_quality_prod.daily_forecast scheduled__2025-03-29T04:00:00+00:00 [running]> on host 04906466de51
[2025-03-30T22:51:32.255+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='paris_air_quality_prod' AIRFLOW_CTX_TASK_ID='daily_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T04:00:00+00:00'
[2025-03-30T22:51:32.257+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-30T22:51:32.270+0000] {data_enriched_predict.py:172} INFO - Début du workflow de prévision
[2025-03-30T22:51:32.315+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-30T22:51:32.317+0000] {data_enriched_predict.py:181} INFO - Exécution de la requête: SELECT * FROM data_warehouse WHERE city = 'Paris'
[2025-03-30T22:51:32.375+0000] {data_enriched_predict.py:183} INFO - Données chargées de la base: 160 lignes
[2025-03-30T22:51:32.376+0000] {data_enriched_predict.py:184} INFO - Colonnes de la base: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure']
[2025-03-30T22:51:33.555+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/data_enriched_predict.py:191 FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
[2025-03-30T22:51:33.556+0000] {data_enriched_predict.py:192} INFO - Données après ajout des données actuelles: 161 lignes
[2025-03-30T22:51:33.557+0000] {data_enriched_predict.py:193} INFO - Colonnes après ajout des données actuelles: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure']
[2025-03-30T22:51:33.557+0000] {data_enriched_predict.py:137} INFO - Données initiales: 161 lignes
[2025-03-30T22:51:33.557+0000] {data_enriched_predict.py:138} INFO - Colonnes disponibles: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure']
[2025-03-30T22:51:33.561+0000] {data_enriched_predict.py:149} INFO - Données avant dropna: 161 lignes
[2025-03-30T22:51:33.562+0000] {data_enriched_predict.py:150} INFO - Colonnes après feature engineering: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure', 'hour', 'day_of_week', 'month']
[2025-03-30T22:51:33.563+0000] {data_enriched_predict.py:154} INFO - Données après dropna: 161 lignes
[2025-03-30T22:51:33.565+0000] {data_enriched_predict.py:162} INFO - Nombre de valeurs NaN par colonne:
city           1
timestamp      0
aqi            0
pm25           1
pm10           1
temperature    0
humidity       0
pressure       0
hour           0
day_of_week    0
month          0
dtype: int64
[2025-03-30T22:51:33.565+0000] {data_enriched_predict.py:220} INFO - Features utilisées pour l'entraînement: ['hour', 'day_of_week', 'month', 'temperature', 'humidity', 'pressure']
[2025-03-30T22:51:33.598+0000] {data_enriched_predict.py:227} INFO - Validation Fold 1 - R²: 1.00
[2025-03-30T22:51:33.620+0000] {data_enriched_predict.py:227} INFO - Validation Fold 2 - R²: -0.02
[2025-03-30T22:51:33.620+0000] {data_enriched_predict.py:231} WARNING - Certains scores de validation sont négatifs, le modèle pourrait ne pas être fiable
[2025-03-30T22:51:33.843+0000] {data_enriched_predict.py:283} INFO - Prévisions enregistrées avec succès pour 16 jours
[2025-03-30T22:51:33.844+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-30T22:51:33.883+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-30T22:51:33.884+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=paris_air_quality_prod, task_id=daily_forecast, run_id=scheduled__2025-03-29T04:00:00+00:00, execution_date=20250329T040000, start_date=20250330T225131, end_date=20250330T225133
[2025-03-30T22:51:33.930+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T22:51:33.980+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T22:51:33.982+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
