[2025-03-30T22:48:48.637+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T22:48:48.685+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast manual__2025-03-30T22:48:37.341816+00:00 [queued]>
[2025-03-30T22:48:48.697+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast manual__2025-03-30T22:48:37.341816+00:00 [queued]>
[2025-03-30T22:48:48.698+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-03-30T22:48:48.713+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): daily_forecast> on 2025-03-30 22:48:37.341816+00:00
[2025-03-30T22:48:48.724+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'paris_air_quality_prod', 'daily_forecast', 'manual__2025-03-30T22:48:37.341816+00:00', '--job-id', '659', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmppkf2hcux']
[2025-03-30T22:48:48.727+0000] {standard_task_runner.py:105} INFO - Job 659: Subtask daily_forecast
[2025-03-30T22:48:48.728+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3312) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T22:48:48.728+0000] {standard_task_runner.py:72} INFO - Started process 3337 to run task
[2025-03-30T22:48:48.880+0000] {task_command.py:467} INFO - Running <TaskInstance: paris_air_quality_prod.daily_forecast manual__2025-03-30T22:48:37.341816+00:00 [running]> on host 04906466de51
[2025-03-30T22:48:49.200+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='paris_air_quality_prod' AIRFLOW_CTX_TASK_ID='daily_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T22:48:37.341816+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T22:48:37.341816+00:00'
[2025-03-30T22:48:49.203+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-30T22:48:49.222+0000] {data_enriched_predict.py:172} INFO - Début du workflow de prévision
[2025-03-30T22:48:49.278+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-30T22:48:49.282+0000] {data_enriched_predict.py:181} INFO - Exécution de la requête: SELECT * FROM data_warehouse WHERE city = 'Paris'
[2025-03-30T22:48:49.348+0000] {data_enriched_predict.py:183} INFO - Données chargées de la base: 160 lignes
[2025-03-30T22:48:49.349+0000] {data_enriched_predict.py:184} INFO - Colonnes de la base: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure']
[2025-03-30T22:48:50.440+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/data_enriched_predict.py:191 FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
[2025-03-30T22:48:50.446+0000] {data_enriched_predict.py:192} INFO - Données après ajout des données actuelles: 161 lignes
[2025-03-30T22:48:50.448+0000] {data_enriched_predict.py:193} INFO - Colonnes après ajout des données actuelles: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure']
[2025-03-30T22:48:50.448+0000] {data_enriched_predict.py:137} INFO - Données initiales: 161 lignes
[2025-03-30T22:48:50.449+0000] {data_enriched_predict.py:138} INFO - Colonnes disponibles: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure']
[2025-03-30T22:48:50.455+0000] {data_enriched_predict.py:149} INFO - Données avant dropna: 161 lignes
[2025-03-30T22:48:50.456+0000] {data_enriched_predict.py:150} INFO - Colonnes après feature engineering: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure', 'hour', 'day_of_week', 'month']
[2025-03-30T22:48:50.462+0000] {data_enriched_predict.py:154} INFO - Données après dropna: 161 lignes
[2025-03-30T22:48:50.465+0000] {data_enriched_predict.py:162} INFO - Nombre de valeurs NaN par colonne:
city           1
timestamp      0
aqi            0
pm25           1
pm10           1
temperature    0
humidity       0
pressure       0
hour           0
day_of_week    0
month          0
dtype: int64
[2025-03-30T22:48:50.466+0000] {data_enriched_predict.py:220} INFO - Features utilisées pour l'entraînement: ['hour', 'day_of_week', 'month', 'temperature', 'humidity', 'pressure']
[2025-03-30T22:48:50.515+0000] {data_enriched_predict.py:227} INFO - Validation Fold 1 - R²: 1.00
[2025-03-30T22:48:50.542+0000] {data_enriched_predict.py:227} INFO - Validation Fold 2 - R²: -0.02
[2025-03-30T22:48:50.543+0000] {data_enriched_predict.py:231} WARNING - Certains scores de validation sont négatifs, le modèle pourrait ne pas être fiable
[2025-03-30T22:48:50.679+0000] {data_enriched_predict.py:284} ERROR - Échec du workflow: 'HistGradientBoostingRegressor' object has no attribute 'estimators_'
Traceback (most recent call last):
  File "/opt/airflow/dags/data_enriched_predict.py", line 259, in train_and_forecast
    for tree in model.named_steps['regressor'].estimators_], axis=0)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HistGradientBoostingRegressor' object has no attribute 'estimators_'
[2025-03-30T22:48:50.688+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 259, in train_and_forecast
    for tree in model.named_steps['regressor'].estimators_], axis=0)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HistGradientBoostingRegressor' object has no attribute 'estimators_'
[2025-03-30T22:48:50.745+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=paris_air_quality_prod, task_id=daily_forecast, run_id=manual__2025-03-30T22:48:37.341816+00:00, execution_date=20250330T224837, start_date=20250330T224848, end_date=20250330T224850
[2025-03-30T22:48:50.770+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-30T22:48:50.792+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 659 for task daily_forecast ('HistGradientBoostingRegressor' object has no attribute 'estimators_'; 3337)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 259, in train_and_forecast
    for tree in model.named_steps['regressor'].estimators_], axis=0)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HistGradientBoostingRegressor' object has no attribute 'estimators_'
[2025-03-30T22:48:50.834+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T22:48:50.894+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T22:48:50.896+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
