[2025-04-17T14:05:13.508+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T14:05:13.556+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline.extract_yellow scheduled__2025-04-17T13:00:00+00:00 [queued]>
[2025-04-17T14:05:13.570+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline.extract_yellow scheduled__2025-04-17T13:00:00+00:00 [queued]>
[2025-04-17T14:05:13.571+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-04-17T14:05:13.587+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): extract_yellow> on 2025-04-17 13:00:00+00:00
[2025-04-17T14:05:13.591+0000] {standard_task_runner.py:72} INFO - Started process 6294 to run task
[2025-04-17T14:05:13.594+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline', 'extract_yellow', 'scheduled__2025-04-17T13:00:00+00:00', '--job-id', '878', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmpu85xvqvo']
[2025-04-17T14:05:13.596+0000] {standard_task_runner.py:105} INFO - Job 878: Subtask extract_yellow
[2025-04-17T14:05:13.841+0000] {task_command.py:467} INFO - Running <TaskInstance: full_pipeline.extract_yellow scheduled__2025-04-17T13:00:00+00:00 [running]> on host 772d115850d3
[2025-04-17T14:05:14.015+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='full_pipeline' AIRFLOW_CTX_TASK_ID='extract_yellow' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-17T13:00:00+00:00'
[2025-04-17T14:05:14.016+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T14:05:14.027+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-17T14:05:14.029+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/pipeline/extract/fetch_yellow_trip.py']
[2025-04-17T14:05:14.035+0000] {subprocess.py:99} INFO - Output:
[2025-04-17T14:05:14.951+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-17T14:05:14.952+0000] {subprocess.py:106} INFO -   File "/opt/airflow/pipeline/extract/fetch_yellow_trip.py", line 26, in <module>
[2025-04-17T14:05:14.956+0000] {subprocess.py:106} INFO -     upload_to_minio(
[2025-04-17T14:05:14.956+0000] {subprocess.py:106} INFO -   File "/opt/airflow/pipeline/extract/fetch_yellow_trip.py", line 22, in upload_to_minio
[2025-04-17T14:05:14.960+0000] {subprocess.py:106} INFO -     s3.upload_file(file_path, bucket_name, object_name)
[2025-04-17T14:05:14.961+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/inject.py", line 145, in upload_file
[2025-04-17T14:05:14.961+0000] {subprocess.py:106} INFO -     return transfer.upload_file(
[2025-04-17T14:05:14.961+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T14:05:14.962+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/transfer.py", line 372, in upload_file
[2025-04-17T14:05:14.962+0000] {subprocess.py:106} INFO -     future.result()
[2025-04-17T14:05:14.962+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 103, in result
[2025-04-17T14:05:14.963+0000] {subprocess.py:106} INFO -     return self._coordinator.result()
[2025-04-17T14:05:14.963+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T14:05:14.964+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 264, in result
[2025-04-17T14:05:14.964+0000] {subprocess.py:106} INFO -     raise self._exception
[2025-04-17T14:05:14.964+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/tasks.py", line 265, in _main
[2025-04-17T14:05:14.964+0000] {subprocess.py:106} INFO -     self._submit(transfer_future=transfer_future, **kwargs)
[2025-04-17T14:05:14.965+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/upload.py", line 589, in _submit
[2025-04-17T14:05:14.965+0000] {subprocess.py:106} INFO -     upload_input_manager.provide_transfer_size(transfer_future)
[2025-04-17T14:05:14.965+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/upload.py", line 244, in provide_transfer_size
[2025-04-17T14:05:14.966+0000] {subprocess.py:106} INFO -     self._osutil.get_file_size(transfer_future.meta.call_args.fileobj)
[2025-04-17T14:05:14.966+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/utils.py", line 254, in get_file_size
[2025-04-17T14:05:14.966+0000] {subprocess.py:106} INFO -     return os.path.getsize(filename)
[2025-04-17T14:05:14.966+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-17T14:05:14.967+0000] {subprocess.py:106} INFO -   File "<frozen genericpath>", line 62, in getsize
[2025-04-17T14:05:14.967+0000] {subprocess.py:106} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'yellow_tripdata_2023-01.parquet'
[2025-04-17T14:05:15.048+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-17T14:05:15.089+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-17T14:05:15.094+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=full_pipeline, task_id=extract_yellow, run_id=scheduled__2025-04-17T13:00:00+00:00, execution_date=20250417T130000, start_date=20250417T140513, end_date=20250417T140515
[2025-04-17T14:05:15.112+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-17T14:05:15.113+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 878 for task extract_yellow (Bash command failed. The command returned a non-zero exit code 1.; 6294)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-17T14:05:15.134+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-17T14:05:15.185+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T14:05:15.190+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
