[2025-03-30T22:34:55.713+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T22:34:55.761+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast manual__2025-03-30T22:34:45.647239+00:00 [queued]>
[2025-03-30T22:34:55.773+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: paris_air_quality_prod.daily_forecast manual__2025-03-30T22:34:45.647239+00:00 [queued]>
[2025-03-30T22:34:55.774+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-03-30T22:34:55.789+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): daily_forecast> on 2025-03-30 22:34:45.647239+00:00
[2025-03-30T22:34:55.797+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'paris_air_quality_prod', 'daily_forecast', 'manual__2025-03-30T22:34:45.647239+00:00', '--job-id', '653', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmp8nckikjw']
[2025-03-30T22:34:55.800+0000] {standard_task_runner.py:105} INFO - Job 653: Subtask daily_forecast
[2025-03-30T22:34:55.801+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2573) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T22:34:55.802+0000] {standard_task_runner.py:72} INFO - Started process 2598 to run task
[2025-03-30T22:34:55.962+0000] {task_command.py:467} INFO - Running <TaskInstance: paris_air_quality_prod.daily_forecast manual__2025-03-30T22:34:45.647239+00:00 [running]> on host 04906466de51
[2025-03-30T22:34:56.306+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='paris_air_quality_prod' AIRFLOW_CTX_TASK_ID='daily_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T22:34:45.647239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T22:34:45.647239+00:00'
[2025-03-30T22:34:56.308+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-30T22:34:56.322+0000] {data_enriched_predict.py:174} INFO - Début du workflow de prévision
[2025-03-30T22:34:56.375+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-30T22:34:56.379+0000] {data_enriched_predict.py:183} INFO - Exécution de la requête: SELECT * FROM data_warehouse WHERE city = 'Paris'
[2025-03-30T22:34:56.472+0000] {data_enriched_predict.py:185} INFO - Données chargées de la base: 160 lignes
[2025-03-30T22:34:56.473+0000] {data_enriched_predict.py:186} INFO - Colonnes de la base: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure']
[2025-03-30T22:34:57.644+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/data_enriched_predict.py:193 FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
[2025-03-30T22:34:57.645+0000] {data_enriched_predict.py:194} INFO - Données après ajout des données actuelles: 161 lignes
[2025-03-30T22:34:57.646+0000] {data_enriched_predict.py:195} INFO - Colonnes après ajout des données actuelles: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure']
[2025-03-30T22:34:57.646+0000] {data_enriched_predict.py:135} INFO - Données initiales: 161 lignes
[2025-03-30T22:34:57.647+0000] {data_enriched_predict.py:136} INFO - Colonnes disponibles: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure']
[2025-03-30T22:34:57.654+0000] {data_enriched_predict.py:151} INFO - Données avant dropna: 161 lignes
[2025-03-30T22:34:57.655+0000] {data_enriched_predict.py:152} INFO - Colonnes après feature engineering: ['city', 'timestamp', 'aqi', 'pm25', 'pm10', 'temperature', 'humidity', 'pressure', 'hour', 'day_of_week', 'month', 'aqi_lag_24h', 'aqi_lag_168h']
[2025-03-30T22:34:57.657+0000] {data_enriched_predict.py:156} INFO - Données après dropna: 161 lignes
[2025-03-30T22:34:57.659+0000] {data_enriched_predict.py:164} INFO - Nombre de valeurs NaN par colonne:
city              1
timestamp         0
aqi               0
pm25              1
pm10              1
temperature       0
humidity          0
pressure          0
hour              0
day_of_week       0
month             0
aqi_lag_24h      24
aqi_lag_168h    161
dtype: int64
[2025-03-30T22:34:57.661+0000] {data_enriched_predict.py:219} INFO - Features utilisées pour l'entraînement: ['aqi_lag_168h', 'aqi_lag_24h', 'day_of_week', 'hour', 'humidity', 'month', 'pm10', 'pm25', 'pressure', 'temperature']
[2025-03-30T22:34:57.668+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/extmath.py:1101 RuntimeWarning: invalid value encountered in divide
[2025-03-30T22:34:57.670+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/extmath.py:1106 RuntimeWarning: invalid value encountered in divide
[2025-03-30T22:34:57.671+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/extmath.py:1126 RuntimeWarning: invalid value encountered in divide
[2025-03-30T22:34:57.757+0000] {data_enriched_predict.py:226} INFO - Validation Fold 1 - R²: 1.00
[2025-03-30T22:34:57.760+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/extmath.py:1101 RuntimeWarning: invalid value encountered in divide
[2025-03-30T22:34:57.761+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/extmath.py:1106 RuntimeWarning: invalid value encountered in divide
[2025-03-30T22:34:57.762+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/extmath.py:1126 RuntimeWarning: invalid value encountered in divide
[2025-03-30T22:34:57.787+0000] {data_enriched_predict.py:226} INFO - Validation Fold 2 - R²: 1.00
[2025-03-30T22:34:57.790+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/extmath.py:1101 RuntimeWarning: invalid value encountered in divide
[2025-03-30T22:34:57.791+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/extmath.py:1106 RuntimeWarning: invalid value encountered in divide
[2025-03-30T22:34:57.792+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/extmath.py:1126 RuntimeWarning: invalid value encountered in divide
[2025-03-30T22:34:57.812+0000] {data_enriched_predict.py:226} INFO - Validation Fold 3 - R²: -0.03
[2025-03-30T22:34:57.943+0000] {data_enriched_predict.py:124} ERROR - Erreur OpenMeteo: Cannot convert tz-naive timestamps, use tz_localize to localize
Traceback (most recent call last):
  File "/opt/airflow/dags/data_enriched_predict.py", line 118, in get_openmeteo_forecast
    df['time'] = df['time'].dt.tz_convert(CITY_CONFIG['timezone'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/accessor.py", line 112, in f
    return self._delegate_method(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/accessors.py", line 134, in _delegate_method
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/datetimes.py", line 281, in tz_convert
    arr = self._data.tz_convert(tz)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/datetimes.py", line 893, in tz_convert
    raise TypeError(
TypeError: Cannot convert tz-naive timestamps, use tz_localize to localize
[2025-03-30T22:34:57.954+0000] {data_enriched_predict.py:274} ERROR - Échec du workflow: Aucune donnée météo récupérée
Traceback (most recent call last):
  File "/opt/airflow/dags/data_enriched_predict.py", line 231, in train_and_forecast
    raise ValueError("Aucune donnée météo récupérée")
ValueError: Aucune donnée météo récupérée
[2025-03-30T22:34:57.957+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 231, in train_and_forecast
    raise ValueError("Aucune donnée météo récupérée")
ValueError: Aucune donnée météo récupérée
[2025-03-30T22:34:58.010+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=paris_air_quality_prod, task_id=daily_forecast, run_id=manual__2025-03-30T22:34:45.647239+00:00, execution_date=20250330T223445, start_date=20250330T223455, end_date=20250330T223458
[2025-03-30T22:34:58.036+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-30T22:34:58.037+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 653 for task daily_forecast (Aucune donnée météo récupérée; 2598)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_enriched_predict.py", line 231, in train_and_forecast
    raise ValueError("Aucune donnée météo récupérée")
ValueError: Aucune donnée météo récupérée
[2025-03-30T22:34:58.070+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T22:34:58.129+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T22:34:58.131+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
